# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msgdef.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmsgdef.proto\x12\x03msg\"#\n\x0bPhoneNumber\x12\t\n\x01\x61\x18\x04 \x01(\x05\x12\t\n\x01\x62\x18\x05 \x01(\t\";\n\x06Person\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\t\x12\x1b\n\x01\x63\x18\x03 \x01(\x0b\x32\x10.msg.PhoneNumberb\x06proto3')



_PHONENUMBER = DESCRIPTOR.message_types_by_name['PhoneNumber']
_PERSON = DESCRIPTOR.message_types_by_name['Person']
PhoneNumber = _reflection.GeneratedProtocolMessageType('PhoneNumber', (_message.Message,), {
  'DESCRIPTOR' : _PHONENUMBER,
  '__module__' : 'msgdef_pb2'
  # @@protoc_insertion_point(class_scope:msg.PhoneNumber)
  })
_sym_db.RegisterMessage(PhoneNumber)

Person = _reflection.GeneratedProtocolMessageType('Person', (_message.Message,), {
  'DESCRIPTOR' : _PERSON,
  '__module__' : 'msgdef_pb2'
  # @@protoc_insertion_point(class_scope:msg.Person)
  })
_sym_db.RegisterMessage(Person)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PHONENUMBER._serialized_start=21
  _PHONENUMBER._serialized_end=56
  _PERSON._serialized_start=58
  _PERSON._serialized_end=117
# @@protoc_insertion_point(module_scope)
